[project]
name = "tiauth-faroe-user-server"
version = "0.1.0"
description = "Helper library for creating a Faroe user server in Python"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Tip ten Brink", email = "75669206+tiptenbrink@users.noreply.github.com" }
]
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]

[tool.uv]
# Only allow packages uploaded at least 3 days ago to guard against supply chain attacks
exclude-newer = "3 days"

[tool.uv.build-backend]
module-name = "tiauth_faroe.user_server"

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.3",
    "ty>=0.0.72",
]
