[project]
name = "sync-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "data"
]


[tool.uv.sources]
data = { workspace = true }
